SELECT * FROM t WHERE x GLOBAL IN (1, 2);
SELECT * FROM t WHERE x GLOBAL NOT IN (1, 2);
SELECT * FROM t WHERE x GLOBAL IN (SELECT y FROM t2);
SELECT * FROM t WHERE x GLOBAL NOT IN (SELECT y FROM t2);
SELECT * FROM t WHERE x GLOBAL IN t2;
SELECT * FROM t WHERE x GLOBAL IN (t2);
SELECT * FROM t WHERE x GLOBAL IN db.t2;
SELECT * FROM t WHERE x global in (1) AND y Global Not In (2);
SELECT * FROM t WHERE x GLOBAL IN (1);
SELECT * FROM t WHERE x GLOBAL IN (NULL, 1, 'a', 1.5, -1, 1 + 2, y * 2);
SELECT * FROM t WHERE x GLOBAL IN ('', '''', 'GLOBAL IN');
SELECT * FROM t WHERE x GLOBAL IN ((1), ((2)), (((3))));
SELECT * FROM t WHERE x GLOBAL IN ((SELECT 1), 2);
SELECT * FROM t WHERE x GLOBAL IN ((SELECT 1));
SELECT * FROM t WHERE x GLOBAL NOT IN (((SELECT 1)), (SELECT 2) + 1);
SELECT * FROM t WHERE x GLOBAL IN (SELECT 1 UNION ALL SELECT 2);
SELECT * FROM t WHERE x GLOBAL IN (SELECT y FROM t2 WHERE z GLOBAL IN (SELECT w FROM t3 WHERE v GLOBAL NOT IN (1)));
SELECT * FROM t WHERE (a, b) GLOBAL IN ((1, 2), (3, 4));
SELECT * FROM t WHERE (a, b) GLOBAL NOT IN (SELECT a, b FROM t2);
SELECT * FROM t WHERE tuple(a, b) GLOBAL IN (SELECT a, b FROM t2);
SELECT * FROM t WHERE (SELECT 1) GLOBAL IN (1, 2);
SELECT * FROM t WHERE toInt32(x) GLOBAL IN (lower('a'), upper('b'));
SELECT * FROM t WHERE CAST(x AS String) GLOBAL IN ('1', '2');
SELECT * FROM t WHERE x GLOBAL IN ([1, 2], [3]);
SELECT * FROM t WHERE arr[1] GLOBAL IN (1, 2);
SELECT * FROM t WHERE tup.1 GLOBAL IN (1, 2);
SELECT * FROM t WHERE NOT x GLOBAL IN (1, 2);
SELECT * FROM t WHERE NOT (x GLOBAL NOT IN (1, 2));
SELECT * FROM t WHERE x GLOBAL IN (1) AND y = 2 OR z GLOBAL NOT IN (3) AND w = 4;
SELECT * FROM t WHERE a = 1 OR x GLOBAL IN (1) AND y BETWEEN 1 AND 2;
SELECT * FROM t WHERE (x GLOBAL IN (1)) IS NULL;
SELECT * FROM t WHERE (x GLOBAL IN (1)) = (y GLOBAL IN (2));
SELECT * FROM t WHERE x GLOBAL IN (1) AND y IN (2) AND z NOT IN (3) AND w GLOBAL NOT IN (4);
SELECT * FROM t WHERE x GLOBAL IN (1) AND EXISTS (SELECT 1 FROM u WHERE u.x GLOBAL IN (1));
SELECT x GLOBAL IN (1, 2) AS flag, x GLOBAL NOT IN (SELECT y FROM t2) FROM t;
SELECT CASE WHEN x GLOBAL IN (1, 2) THEN 'a' WHEN x GLOBAL NOT IN (SELECT y FROM t2) THEN 'b' ELSE 'c' END FROM t;
SELECT if(x GLOBAL IN (1), 1, 0), multiIf(x GLOBAL NOT IN (2), 1, 0) FROM t;
SELECT count() FROM t GROUP BY x GLOBAL IN (1, 2) HAVING count() GLOBAL IN (SELECT c FROM counts);
SELECT * FROM t ORDER BY x GLOBAL IN (1, 2) DESC, y GLOBAL NOT IN (3) ASC LIMIT 10;
SELECT * FROM t PREWHERE x GLOBAL IN (SELECT y FROM t2) WHERE z GLOBAL NOT IN (1);
SELECT * FROM t JOIN u ON t.x = u.x AND u.y GLOBAL IN (SELECT y FROM t2);
SELECT * FROM t LEFT JOIN u ON t.x GLOBAL IN (1, 2) WHERE u.y GLOBAL NOT IN (3);
SELECT * FROM t ARRAY JOIN arr WHERE arr GLOBAL IN (1, 2);
SELECT arrayFilter(v -> v GLOBAL IN (1, 2), arr) FROM t;
SELECT * FROM (SELECT * FROM t WHERE x GLOBAL IN (1)) AS sub WHERE sub.x GLOBAL NOT IN (2);
WITH c AS (SELECT 1 AS v) SELECT * FROM t WHERE x GLOBAL IN (SELECT v FROM c);
SELECT * FROM t WHERE x GLOBAL IN (1, 2) SETTINGS max_threads = 1;
SELECT * FROM t WHERE x GLOBAL IN (1) UNION ALL SELECT * FROM t WHERE x GLOBAL NOT IN (2);
SELECT * FROM t WHERE x GLOBAL IN (SELECT y FROM t2) ORDER BY x LIMIT 1 BY x;
SELECT sum(x) OVER (PARTITION BY y GLOBAL IN (1, 2)) FROM t;
INSERT INTO t2 SELECT * FROM t WHERE x GLOBAL IN (1, 2);
DELETE FROM t WHERE x GLOBAL IN (SELECT y FROM t2);
UPDATE t SET y = 1 WHERE x GLOBAL IN (SELECT y FROM t2);
CREATE VIEW v AS SELECT * FROM t WHERE x GLOBAL IN (1, 2);
SELECT /* GLOBAL IN */ * FROM t WHERE x GLOBAL -- NOT
IN (1, 2);
SELECT * FROM t WHERE x
GLOBAL
NOT
IN
(1,
2)